### ISSUE TITLE
Can't find support for generic processor_token

### ISSUE THREAD

**Issue by arass** [plaid/plaid-java#196]
Hi. Support for generic processor_token is not there. 

If someone can point my nose at it - would be great. Bank is demanding we use that instead of public key. 

Here's what I'd like to be able to do through Java:

curl -H "Content-Type: application/json" -X POST -d '{"client_id":"{{ CLIENT_ID}}","secret":"{{ SECRET }}","access_token":"{{ ACCESS_TOKEN }}", **"processor" : "prime_trust"**,}' https://sandbox.plaid.com/processor/token/create

Seems like there are a bunch of these processor codes Plaid houses. I only saw processor_token for Dwolla and Apex. Would be nice to make this a generic functionality (to get a processor token for a given ACH processor).

**Comment by daniellacoste** [comment]
Hey @arass,

Daniel from Plaid Support here - thanks for the question.

> Support for generic processor_token is not there. [...] Would be nice to make this a generic functionality (to get a processor token for a given ACH processor).

We are working on a generic implementation for this client library (and I see [your comment here](https://github.com/plaid/plaid-python/pull/187#issuecomment-593552539)), but I can’t share an ETA for when this work will be complete. If this issue is pressing, I suggest that you call the endpoint directly (instead of using the client library).

I hope this helps - thanks for your patience in the meantime!

Cheers,
Daniel
Plaid Support

**Comment by arass** [comment]
Thanks, Daniel.
Yeah, I wrote a RestTemplate call to do this for now. 
But this seems to be THE way banks now want you to use Plaid. So I think you'll start getting this request more and more.
