### ISSUE TITLE
Institutions implementation

### ISSUE THREAD

**Issue by dudehook** [plaid/plaid-java#25]
I'm implementing the institutions part of the public client.

**Comment by truptigosavi83** [comment]
Hi dudehook,
Could you please tell us when this institutions part will done? I am also using public client and getallInstitutions method but for this I am getting error of httpclient such as "java.lang.ClassNotFoundException: org.apache.http.config.Lookup" I tried with adding dependency in pom.xml file but this not much help me

**Comment by dudehook** [comment]
Oh my, that was a year and a half ago.  I stopped working on that project, so I don't remember if I finished this.  I'll take a look and see if I got it done or not.

**Comment by truptigosavi83** [comment]
Hi David I solve it by using dependency as 
<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>4.4.1</version>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpcore</artifactId>
			<version>4.4.5</version>
		</dependency>

Now I wanted to know is their any other api exist which can give us list of institute and their images in response?

**Comment by michaelckelly** [comment]
@dudehook @truptigosavi83 - This library has since been rewritten for Plaid's [updated API][1] and released as version `2.1.0`. The [legacy Java library][2] is still available. This issue may still be relevant for that project.

[1]: https://blog.plaid.com/improving-our-api
[2]: https://github.com/plaid/plaid-java-legacy
