### ISSUE TITLE
updateTransactions seems inconsistent

### ISSUE THREAD

**Issue by dudehook** [plaid/plaid-java#27]
The two calls named updateTransactions in the user client use different URLs, one uses /connect and the other uses /connect/get.  The documentation suggests that retrieving transactions should use /connect/get and initial setup should use /connect.

I suggest that the updateTransactions (possibly renamed to getTransactions) use /connect/get.

I can change this if we agree.

**Comment by michaelckelly** [comment]
@shawndellysse - This library has since been rewritten for Plaid's [updated API][1] and released as version `2.1.0`. The [legacy Java library][2] is still available. This issue may still be relevant for that project.

[1]: https://blog.plaid.com/improving-our-api
[2]: https://github.com/plaid/plaid-java-legacy
