### ISSUE TITLE
Implementation for info using an access_token is missing

### ISSUE THREAD

**Issue by georgetheka** [plaid/plaid-java#36]
The only way to call the info service is via (https://github.com/plaid/plaid-java/blob/master/src/main/java/com/plaid/client/PlaidUserClient.java#L50) which requires credentials. There is no way with the current SDK to take advantage of link and acces_token to make an info request.

**Comment by michaelckelly** [comment]
@georgetheka  - This library has since been rewritten for Plaid's [updated API][1] and released as version `2.1.0`. The [legacy Java library][2] is still available. This issue may still be relevant for that project.

[1]: https://blog.plaid.com/improving-our-api
[2]: https://github.com/plaid/plaid-java-legacy
