### ISSUE TITLE
LinkTokenCreateRequestAuth does not include option for sms_microdeposits_verification_enabled

### ISSUE THREAD

**Issue by Adrianczuk** [plaid/plaid-java#414]
According to the recent changelog [here](https://plaid.com/docs/changelog/), sms verification has been enabled by default;
>Released the [Text Message Verification](https://plaid.com/docs/auth/coverage/same-day/#using-text-message-verification) flow for Same-Day Micro-deposits. This new, non-breaking change can increase conversion of micro-deposit verification by up to 15%. Currently, Text Message Verification is opt-in, and will transition to opt-out in March.

I don't see any options in `LinkTokenCreateRequestAuth` for enabling or disabling the `sms_microdeposits_verification_enabled` boolean. This flag is mentioned [here](https://plaid.com/docs/auth/coverage/same-day/#using-text-message-verification), in the link token create request example:
```
{
  // Other /link/token/create configuration data goes here
  webhook: 'https://webhook.sample.com',
  auth: {
    same_day_microdeposits_enabled: true,
    sms_microdeposits_verification_enabled: true,
  },
}
```
Can we get this added? Thanks!

**Comment by phoenixy1** [comment]
@Adrianczuk yes this is due to an error in the API specification file used to generate the client libraries 😬 the team has already pushed a fix, so this will be resolved in the next monthly client library release. If you need this disabled sooner than that, you can let me (or your account manager, if you have one) know your client ID and request that this be disabled for your team by default.

**Comment by Adrianczuk** [comment]
Thanks for the update!
