### ISSUE TITLE
Change ch.qos.logback.logback-classic to optional dependency

### ISSUE THREAD

**Issue by mspiegel** [plaid/plaid-java#62]
I think concrete logging implementations should not be included as transitive dependencies in a library.

**Comment by michaelckelly** [comment]
@mspiegel - This library has since been rewritten for Plaid's [updated API][1] and released as version `2.1.0`. The [legacy Java library][2] is still available. This issue may still be relevant for that project.

[1]: https://blog.plaid.com/improving-our-api
[2]: https://github.com/plaid/plaid-java-legacy
