### ISSUE TITLE
InfoResponse 

### ISSUE THREAD

**Issue by blaketanon** [plaid/plaid-java#67]
How do I get an InfoResponse from Link, I don't have the username/password for credentials?

InfoResponse info(Credentials credentials, String type, InfoOptions options);

**Comment by michaelckelly** [comment]
@blaketanon - This library has since been rewritten for Plaid's [updated API][1] and released as version `2.1.0`. The [legacy Java library][2] is still available. This issue may still be relevant for that project.

[1]: https://blog.plaid.com/improving-our-api
[2]: https://github.com/plaid/plaid-java-legacy
