### ISSUE TITLE
Android Integration

### ISSUE THREAD

**Issue by HeathNaylor** [plaid/plaid-java#84]
I am wanting to use Plaid for an Android application, however it is improper to use the client id or secret in an end-user binary as it can be exposed via fairly trivial means. Would it be accurate for me to make the assumption that I would build a service that lives on my own web server to store these credentials and then have my Android application interface with that service via http/https requests or is there a way that I would be able to leverage the Java library directly and securely on Android devices?

**Comment by michaelckelly** [comment]
@HeathNaylor - Thanks for the question! You're spot on that you would *not* want to include your client ID and secret in your app itself as it could then be easily compromised.

You can easily embed [Plaid Link](https://github.com/plaid/link) as a Webview within your Android app (or on another platform). You initialize Link with your `public_key` rather than client ID or secret and Link handles the end-to-end authentication flow between your user, Plaid, and the financial institution!
