### ISSUE TITLE
Plaid generating public token in production mode

### ISSUE THREAD

**Issue by sashasami03** [plaid/plaid-java#85]
I am trying to generate public token in production environment ( using productionBaseUrl ) so that I can later invoke other endpoints. I am using curl request to generate the public token 

 curl -X POST https://production.plaid.com/link/item/create  -H 'content-type: application/json'  -d '{
    "credentials": {
        "username": "user_good",
        "password": "pass_good"
    },
    "initial_products": [
        "transactions"
    ],
    "institution_id": "ins_4",
    "public_key": "87ff65ae5aedc630bb08d00bb4ee64"
}'

Its works fine for sandbox. Maybe the credentials are dummy. But now I am getting the error 

 "display_message": null,
  "error_code": "RECAPTCHA_REQUIRED",
  "error_message": "This request requires additional verification via recaptcha. Please resubmit request 
   with recaptcha token included",
  "error_type": "RECAPTCHA_ERROR",
  "request_id": "W9gm9"

How to I get hold of public tokens in production environment. So that I can test other endpoints in my integration using the plaid library.

**Comment by michaelckelly** [comment]
@sashasami03 You should not be using the Link-related API endpoints directly, but instead through the Plaid Link module. Once Link hands off the `public_token`, you send it to your backend app server and then make a request to `/item/public_token/exchange` to exchange the Link `public_token` for an API `access_token`.

**Comment by sneko** [comment]
Hi @michaelckelly ,

I have a specific case where I need to login the user to 2 Plaid accounts (so 2 different public_key). I want to make my user going through the onboarding just once.

I thought about calling directly the API endpoint with user credentials once with publicKeyA and then, same request but with publicKeyB. That's the only easy way I "imagined" to make it simple since I didn't find an official way. Have you encountered this use case?

If not, from your answer you say ` You should not be using the Link-related API endpoints directly ` , I "should not" or is it a requirement "I have to not use direct endpoint" (legally speaking...)?

Thank you,

My question is currently open with the support: #97386
